spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hillel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

    open-in-view: false

jwt:
  key:
    expiration: 604800000

  signing:
    key: iuLTU8rq83ssfe4gfege5ge5hryjtyumjt7mt7mh6iu

server:
  port: 8080

logging:
  level:
    org:
      springframework: info
      hibernate: error
